FROM spike2044/kube-eye-export-server:v0.1.2

WORKDIR /app
COPY ./dist ./dist
COPY ./v3dist ./v3dist
COPY ./assets ./assets
COPY ./Config.toml ./Config.toml
COPY ./client_config.yaml ./client_config.yaml