name: Rust Release and Docker Image

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build Rust Binaries for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenSSL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Install cross
        uses: taiki-e/install-action@cross

      - name: Build with cross
        run: |
          cross build --release --target ${{ matrix.target }}
          mkdir -p dist
          cp target/${{ matrix.target }}/release/app dist/app-${{ matrix.target }}

      - name: Upload Linux binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/app-${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build for macOS M1
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenSSL (macOS)
        run: |
          brew install pkg-config openssl@3

      - name: Set OPENSSL_DIR
        run: echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV

      - name: Install Rust target
        run: rustup target add aarch64-apple-darwin

      - name: Build for macOS M1
        run: |
          cargo build --release --target aarch64-apple-darwin
          mkdir -p dist
          cp target/aarch64-apple-darwin/release/kube-eye-export-server dist/app-aarch64-apple-darwin

      - name: Upload macOS binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/app-aarch64-apple-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: spike2044/kube-eye-export-server:${{ github.ref_name }}
