name: Rust Release Docker Image

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: spike2044/kube-eye-export-server

jobs:
  build-amd64:
    name: Build and Push amd64 Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push amd64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-amd64

  build-arm64:
    name: Build and Push arm64 Image
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push arm64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-arm64

  # 合并为 multi-arch 镜像
  manifest:
    name: Create and Push Multi-Arch Manifest
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          echo "Creating manifest for ${{ env.IMAGE_NAME }}:${{ github.ref_name }} with amd64 and arm64 images"
          echo "Amending with amd64: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-amd64"
          echo "Amending with arm64: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-arm64"

          docker manifest create ${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
            --amend ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-amd64 \
            --amend ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-arm64
          
          echo "Pushing manifest ${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
          docker manifest push ${{ env.IMAGE_NAME }}:${{ github.ref_name }}